{% set version = "13.1.115" %}
{% set cuda_version = "13.1" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64 and arm_variant_type == "sbsa"]
{% set platform = "linux-aarch64" %}  # [aarch64 and arm_variant_type == "tegra"]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

{% set soname = version.split(".")[0] %}

{% set sha256 = "08d9c50c046bb5e71b21951c7f8032003d7997040d9e8adc6a3a5cb172b6f3fb" %}  # [linux64]
{% set sha256 = "9b11db1e5fcca2431f49a6304b9af452add35185ef9864ba8d51d90246fe93af" %}  # [aarch64]
{% set sha256 = "17c7996e72e3d6ec04fb20e512ef45789b9e580dfe51eabe3cb8298d5e280d33" %}  # [win]

package:
  name: cuda-ctadvisor-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_ctadvisor/{{ platform }}/cuda_ctadvisor-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1  # [linux]

outputs:
  - name: cuda-ctadvisor
    build:                           # [win]
      script:                        # [win]
         - move bin\* %LIBRARY_BIN%  # [win]
    files:             # [linux]
      - bin/ctadvisor  # [linux]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf <0.18.0                                # [linux]
      files:
        - test-rpath.sh                                   # [linux]
      commands:
        - test -f $PREFIX/bin/ctadvisor                   # [linux]
        - bash test-rpath.sh                              # [linux]
        - if not exist %LIBRARY_BIN%\ctadvisor.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: ctadvisor is a tool that helps users analyze the compilation time of their CUDA C++ code and provides suggestions to reduce it.
  description:
    CUDA Compile Time Advisor (ctadvisor) analyzes trace files containing compilation
    time information generated by NVCC or NVRTC. ctadvisor identifies compilation
    bottlenecks that take significant amount of time, for examples, template
    instantiation and headers processing. The tool provides users with suggestions
    to reduce compilation time.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  feedstock-name: cuda-ctadvisor
  recipe-maintainers:
    - conda-forge/cuda
